AllCops:
  Exclude:
    - 'spec/**'
    - 'demo.rb'

#Metrics/AbcSize:
#  Max: 37

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 13

#Naming/PredicateName:
#  Exclude:
#    - 'movie.rb'

Style/Documentation:
  Enabled: false