AllCops:
  Exclude:
    - 'spec/**'

Lint/UselessAssignment:
  Exclude:
    - 'demo.rb'

Metrics/AbcSize:
  Max: 37

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Naming/PredicateName:
  Exclude:
    - 'movie.rb'

Style/CaseEquality:
  Exclude:
    - 'movie.rb'

Style/Documentation:
  Enabled: false